AE_Santander_Coders_2023_airbnb:
  outputs:
    dev:
      dbname: BD_AIRBNB
      host: localhost
      pass: d50hl38e
      port: 5432
      schema: public
      threads: 1
      type: postgres
      user: postgres
  target: dev
